baseURL: https://tiliavir.github.io/rezepte/
title: Die Gute-Sachen Liste
theme: gochowdown

languageCode: de-de
defaultcontentlanguage: de
languages:
  de:
    laguagedirection: ltr

paginate: 20
canonifyurls: true
pygmentsstyle: monokai
pygmentscodefences: true
pygmentscodefencesguesssyntax: true
pygmentsOptions: "linenos=table"

permalinks:
  posts: /posts/:year/:month/:title

params:
  author: Tiliavir & Eninba
  description: Unsere Lieblingsrezepte an einem Ort gesammelt und so einfach wie möglich beschreiben. Abgesehen von Lynns Büchern, natürlich - die sind schon perfekt :-)
  keywords:
  - Rezepte
  - Kochen
  - Backen
  favicon_32: favicon-32x32.png
  favicon_16: favicon-16x16.png
  footercontent:
  hidecredits: false
  hidecopyright: true
  showNavTitle: true
  custom_css:
    - style.css

menu:
  main:
    - name: Kategorie
      weight: 1
      url: /category/
    - name: Küche
      weight: 2
      url: /cuisine/
    - name: Tags
      weight: 3
      url: /tags/
    - name: Janine
      weight: 4
      url: /janines-liste/
    - name: Markus
      weight: 5
      url: /markus-liste/
    - name: Einkaufsliste
      weight: 6
      url: /einkaufsliste/

taxonomies:
  category: category
  cuisine: cuisine
  tag: tags

disableKinds:
  - "RSS"
