baseURL: https://tiliavir.github.io/rezepte/
languageCode: de-de
title: Die Gute-Sachen Liste
theme: gochowdown
defaultcontentlanguage: de
paginate: 20
canonifyurls: true
pygmentsstyle: monokai
pygmentscodefences: true
pygmentscodefencesguesssyntax: true
pygmentsOptions: "linenos=table"
permalinks:
  posts: /posts/:year/:month/:title
params:
  author: Tiliavir
  description:
  keywords: 'recipes'
  favicon_32: /images/favicon-32x32.png
  favicon_16: /images/favicon-16x16.png
  footercontent:
  hidecredits: false
  hidecopyright: true
  showNavTitle: true
  custom_css:
    - style.css
menu:
  main:
    - name: Kategorie
      weight: 1
      url: /category/
    - name: Küche
      weight: 2
      url: /cuisine/
    - name: Tags
      weight: 3
      url: /tags/
    - name: Janine
      weight: 4
      url: /janines-liste/
    - name: Markus
      weight: 5
      url: /markus-liste/
taxonomies:
  category: category
  cusine: cuisine
  tag: tags
